server:
  port: 4000
spring:
  application:
    name: furniture-miley
  datasource:
    url: jdbc:mysql://localhost:3306/bd_furniture-miley?createDatabaseIfNotExist=true
    username: root
    password: system
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
    expiration: 36000