server:
  port: 4000
spring:
  application:
    name: furniture-miley
  datasource:
    url: jdbc:mysql://localhost:3306/bd_furniture-miley?createDatabaseIfNotExist=true
    username: root
    password: system
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: cortezkevinq@gmail.com
    password: vdtqvbxmuijmfhlm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: smtp.gmail.com
jwt:
  secret: ThisIsSecretForJWTHS512SignatureAlgorithmThatMUSTHave64ByteLength
  expiration: 36000

front:
  url: http://localhost:3000